### ISSUE TITLE
Is Youtube UnHooked available as opensource?

### ISSUE THREAD

**Issue by james-prado** [pamelafox/youtube-feed-hider#2]
Hey, I've been using the extension for years and I love it. I want to make a few tweaks just for myself, is the code available as opensource?

**Comment by pamelafox** [comment]
Yep! You're posting an issue in its open source repository. Just click "Code" or go here: https://github.com/pamelafox/youtube-feed-hider 
Pull requests welcome.

**Comment by james-prado** [comment]
ooh I didn't realize it was just a css file 🤦‍♂️ 

I was so focused on removing elements from the page with js I didn't think to just use css. Thanks!
